const KEY='unipop-admin-data-v1';
const demo={version:1,updatedAt:new Date().toISOString(),locations:[{id:'belval',name:'UniPop Belval',aliases:['Belval','UniPop Esch','Site Belval'],address:'14, Porte de France\nL-4360 Esch-sur-Alzette',description:'Le site UniPop Belval est situé au cœur du quartier universitaire. Accès facile en train, bus ou voiture.',lat:49.5001,lng:5.9483,website:'https://www.unipop.lu',phone:'+352 247-88650',email:'',parking:'Parking Belval Plaza',parkingInfo:'À environ 5 minutes à pied.',transport:'Gare Belval-Université',transportInfo:'Train et lignes de bus à proximité.',accessInfo:'Entrée principale côté parvis.',pmr:true,active:true,hero:'',gallery:[],media:[],plans:[],tutorials:[{title:'Accéder au bâtiment',url:''}],rooms:[{id:'belval-demo',name:'Salle exemple',floor:'1',description:'Salle de démonstration'}]},{id:'ettelbruck',name:'UniPop Ettelbruck',aliases:['Ettelbruck'],address:'Ettelbruck',description:'',lat:49.847,lng:6.104,active:true,hero:'',gallery:[],media:[],plans:[],tutorials:[],rooms:[]},{id:'niederanven',name:'UniPop Niederanven',aliases:['Niederanven'],address:'Niederanven',description:'',lat:49.651,lng:6.26,active:true,hero:'',gallery:[],media:[],plans:[],tutorials:[],rooms:[]}]};
let data=load(), currentId=data.locations[0]?.id||null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(demo)}catch{return structuredClone(demo)}}
function persist(msg='Enregistré'){data.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));stats();toast(msg)}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function current(){return data.locations.find(x=>x.id===currentId)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderList(filter=''){let rows=data.locations.filter(x=>(x.name+' '+(x.aliases||[]).join(' ')).toLowerCase().includes(filter.toLowerCase()));$('#locationList').innerHTML=rows.map(x=>`<div class="location-item ${x.id===currentId?'active':''}" data-id="${esc(x.id)}"><img src="${x.hero||''}"><div><b>${esc(x.name)}</b><small>${esc((x.address||'').split('\n').pop())}</small></div><span>⋮</span></div>`).join('');$('#lieuCount').textContent=data.locations.length;$$('.location-item').forEach(el=>el.onclick=()=>{currentId=el.dataset.id;renderList($('#search').value);fill()})}
function fill(){let x=current();if(!x)return;$$('[data-field]').forEach(el=>{let f=el.dataset.field;if(el.type==='checkbox')el.checked=!!x[f];else el.value=f==='aliases'?(x.aliases||[]).join(', '):(x[f]??'')});$('#heroDrop').classList.toggle('has',!!x.hero);$('#heroImg').src=x.hero||'';renderGallery();renderMedia();renderPlans();renderTuts();updateMap();previewData()}
function readFields(){let x=current();if(!x)return;$$('[data-field]').forEach(el=>{let f=el.dataset.field,v=el.type==='checkbox'?el.checked:el.value;if(f==='aliases')v=v.split(',').map(s=>s.trim()).filter(Boolean);if(['lat','lng'].includes(f))v=v===''?'':Number(v);x[f]=v});if(!x.id)x.id='lieu-'+Date.now()}
function fileToData(file){return new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function addImages(files,target){let x=current();x[target]=x[target]||[];for(let f of files){let src=await fileToData(f);x[target].push({name:f.name,type:f.type,src})}persist('Fichier ajouté');fill()}
function renderGallery(){let x=current();$('#gallery').innerHTML=(x.gallery||[]).map((g,i)=>`<div class="thumb"><img src="${g.src}"><button data-g="${i}">×</button></div>`).join('');$$('[data-g]').forEach(b=>b.onclick=()=>{x.gallery.splice(+b.dataset.g,1);persist();renderGallery()})}
function renderMedia(){let x=current();$('#mediaGrid').innerHTML=(x.media||[]).map((m,i)=>`<div class="media-card">${m.type?.startsWith('image')?`<img src="${m.src}">`:'<div style="height:120px;display:grid;place-items:center;font-size:42px">▧</div>'}<button data-m="${i}">×</button><b>${esc(m.name)}</b></div>`).join('')||'<p>Aucun média.</p>';$$('[data-m]').forEach(b=>b.onclick=()=>{x.media.splice(+b.dataset.m,1);persist();renderMedia()})}
function renderPlans(){let x=current();$('#planGrid').innerHTML=(x.plans||[]).map((m,i)=>`<div class="file-card"><button data-p="${i}">×</button><b>▱ ${esc(m.name)}</b><p>${esc(m.type||'document')}</p></div>`).join('')||'<p>Aucun plan.</p>';$$('[data-p]').forEach(b=>b.onclick=()=>{x.plans.splice(+b.dataset.p,1);persist();renderPlans()})}
function renderTuts(){let x=current();$('#tutList').innerHTML=(x.tutorials||[]).map((t,i)=>`<div class="tutorial"><input value="${esc(t.title)}" data-ti="${i}"><input value="${esc(t.url)}" placeholder="URL vidéo / document" data-tu="${i}"><button class="danger" data-td="${i}">×</button></div>`).join('')||'<p>Aucun tutoriel.</p>';$$('[data-ti]').forEach(e=>e.oninput=()=>x.tutorials[+e.dataset.ti].title=e.value);$$('[data-tu]').forEach(e=>e.oninput=()=>x.tutorials[+e.dataset.tu].url=e.value);$$('[data-td]').forEach(e=>e.onclick=()=>{x.tutorials.splice(+e.dataset.td,1);persist();renderTuts()})}
function updateMap(){let x=current(),lat=Number(x.lat)||49.6116,lng=Number(x.lng)||6.1319;$('#mapFrame').src=`https://www.openstreetmap.org/export/embed.html?bbox=${lng-.01}%2C${lat-.006}%2C${lng+.01}%2C${lat+.006}&layer=mapnik&marker=${lat}%2C${lng}`}
function stats(){let loc=data.locations, rooms=loc.reduce((a,x)=>a+(x.rooms?.length||0),0),tuts=loc.reduce((a,x)=>a+(x.tutorials?.length||0),0),med=loc.reduce((a,x)=>a+(x.gallery?.length||0)+(x.media?.length||0)+(x.hero?1:0),0);$('#statLieux').textContent=loc.length;$('#statSalles').textContent=rooms;$('#statTuts').textContent=tuts;$('#statMedia').textContent=med;$('#lastUpdate').textContent='Dernière mise à jour '+new Date(data.updatedAt).toLocaleString('fr-LU')}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function previewData(){let x=current();if(!x)return;$('#pHero').src=x.hero||'';$('#pName').textContent=x.name||'';$('#pAddress').textContent=x.address||'';$('#pParking').textContent='🅿 '+(x.parking||'Parking non renseigné');$('#pTransport').textContent='▣ '+(x.transport||'Transport non renseigné');$('#pDesc').textContent=x.description||''}
function exportData(){readFields();persist('Données préparées');let clean=JSON.stringify(data,null,2),blob=new Blob([clean],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='unipop-go-lieux.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function generic(view){$('#lieuxView').classList.add('hidden');$('#genericView').classList.remove('hidden');let title={dashboard:'Tableau de bord',salles:'Salles',tutorials:'Tutoriels',plans:'Plans',media:'Médias'}[view];$('#genericTitle').textContent=title;let items=[];if(view==='dashboard')items=data.locations.map(x=>({h:x.name,p:`${x.rooms?.length||0} salles · ${x.gallery?.length||0} images`}));if(view==='salles')data.locations.forEach(x=>(x.rooms||[]).forEach(r=>items.push({h:r.name,p:x.name+' · '+(r.floor||'')})));if(view==='tutorials')data.locations.forEach(x=>(x.tutorials||[]).forEach(r=>items.push({h:r.title,p:x.name})));if(view==='plans')data.locations.forEach(x=>(x.plans||[]).forEach(r=>items.push({h:r.name,p:x.name})));if(view==='media')data.locations.forEach(x=>(x.media||[]).forEach(r=>items.push({h:r.name,p:x.name})));$('#genericContent').innerHTML=items.map(i=>`<div class="generic-card"><h3>${esc(i.h)}</h3><p>${esc(i.p)}</p></div>`).join('')||'<p>Aucune donnée.</p>';$('#pageTitle').textContent=title}
$$('nav button[data-view]').forEach(b=>b.onclick=()=>{$$('nav button[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view==='lieux'){$('#lieuxView').classList.remove('hidden');$('#genericView').classList.add('hidden');$('#pageTitle').textContent='Lieux & Salles'}else generic(b.dataset.view)})
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
$('#search').oninput=e=>renderList(e.target.value);$('#saveBtn').onclick=()=>{readFields();persist();renderList($('#search').value);fill()};$('#addLieu').onclick=()=>{let id='lieu-'+Date.now();data.locations.unshift({id,name:'Nouveau lieu',aliases:[],address:'',description:'',lat:'',lng:'',active:true,hero:'',gallery:[],media:[],plans:[],tutorials:[],rooms:[]});currentId=id;persist('Nouveau lieu créé');renderList();fill()};$('#deleteLieu').onclick=()=>{if(!current()||!confirm('Supprimer ce lieu ?'))return;data.locations=data.locations.filter(x=>x.id!==currentId);currentId=data.locations[0]?.id||null;persist('Lieu supprimé');renderList();fill()};
$('#heroFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;current().hero=await fileToData(f);persist('Photo principale ajoutée');fill()};$('#addGallery').onclick=()=>$('#galleryFile').click();$('#galleryFile').onchange=e=>addImages(e.target.files,'gallery');$('#mediaUploadBtn').onclick=()=>$('#mediaFile').click();$('#mediaFile').onchange=e=>addImages(e.target.files,'media');$('#planUploadBtn').onclick=()=>$('#planFile').click();$('#planFile').onchange=e=>addImages(e.target.files,'plans');$('#addTut').onclick=()=>{current().tutorials=current().tutorials||[];current().tutorials.push({title:'Nouveau tutoriel',url:''});renderTuts()};
$('#googleMaps').onclick=()=>{let x=current();window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent((x.lat&&x.lng)?x.lat+','+x.lng:x.address)}`,'_blank')};$('#appleMaps').onclick=()=>{let x=current();window.open(`https://maps.apple.com/?q=${encodeURIComponent(x.name)}&ll=${x.lat},${x.lng}`,'_blank')};
$('#exportBtn').onclick=$('#exportTop').onclick=exportData;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());if(!Array.isArray(j.locations))throw 0;data=j;currentId=data.locations[0]?.id||null;persist('Import réussi');renderList();fill()}catch{alert('Fichier JSON invalide')}};$('#resetBtn').onclick=()=>{if(confirm('Réinitialiser les données locales ?')){data=structuredClone(demo);currentId=data.locations[0].id;persist('Données réinitialisées');renderList();fill()}};
$('#previewBtn').onclick=()=>{readFields();previewData();$('#previewModal').classList.remove('hidden')};$('#closePreview').onclick=()=>$('#previewModal').classList.add('hidden');$('#previewModal').onclick=e=>{if(e.target.id==='previewModal')$('#previewModal').classList.add('hidden')};
renderList();fill();stats();
